name: Lint

on:
  push:
    branches:
      - master
    paths:
      - "lib/**"
      - "test/**"

jobs:
  lint-fmt:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout tree
        uses: actions/checkout@v3

      - name: Set-up OCaml 5.0
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.0"
          dune-cache: true

      - name: Lint fmt
        uses: ocaml/setup-ocaml/lint-fmt@v2

      - name: Lint doc
        uses: ocaml/setup-ocaml/lint-doc@v2
